package fr.formation.afpa.domain;
// Generated 7 mai 2021 11:42:56 by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name = "compte", catalog = "bd", uniqueConstraints = @UniqueConstraint(columnNames = "login"))
public class Compte implements java.io.Serializable {

	private Integer id;
	private String login;
	private String password;
	private int customerCustId;

	public Compte() {
	}

	public Compte(int customerCustId) {
		this.customerCustId = customerCustId;
	}

	public Compte(String login, String password, int customerCustId) {
		this.login = login;
		this.password = password;
		this.customerCustId = customerCustId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "login", unique = true, length = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "customer_CUST_ID", nullable = false)
	public int getCustomerCustId() {
		return this.customerCustId;
	}

	public void setCustomerCustId(int customerCustId) {
		this.customerCustId = customerCustId;
	}

}
